# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
#
default: &default
  adapter: postgresql
  encoding: unicode
# ----- Change ----
  host: localhost
  port: 5432
  username: postgres
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
# -----------------
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
